# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yy2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("仪表检测")
        Form.resize(641, 494)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.tabWidget.setMaximumSize(QtCore.QSize(641, 481))
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.pushButtoncamer = QtWidgets.QPushButton(self.tab1)
        self.pushButtoncamer.setGeometry(QtCore.QRect(20, 130, 75, 61))
        self.pushButtoncamer.setObjectName("pushButtoncamer")
        self.pushButtonexit = QtWidgets.QPushButton(self.tab1)
        self.pushButtonexit.setGeometry(QtCore.QRect(20, 230, 75, 61))
        self.pushButtonexit.setObjectName("pushButtonexit")
        self.labelimg = QtWidgets.QLabel(self.tab1)
        self.labelimg.setGeometry(QtCore.QRect(110, 20, 491, 381))
        self.labelimg.setText("")
        self.labelimg.setObjectName("labelimg")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.layoutWidget = QtWidgets.QWidget(self.tab2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelinterval = QtWidgets.QLabel(self.layoutWidget)
        self.labelinterval.setObjectName("labelinterval")
        self.gridLayout.addWidget(self.labelinterval, 1, 0, 1, 1)
        self.labeltime = QtWidgets.QLabel(self.layoutWidget)
        self.labeltime.setObjectName("labeltime")
        self.gridLayout.addWidget(self.labeltime, 0, 0, 1, 1)
        self.record_minute = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.record_minute.setMaximum(1000)
        self.record_minute.setObjectName("record_minute")
        self.gridLayout.addWidget(self.record_minute, 1, 1, 1, 1)
        self.pushButtonbegin = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonbegin.setCheckable(False)
        self.pushButtonbegin.setChecked(False)
        self.pushButtonbegin.setAutoRepeatInterval(300)
        self.pushButtonbegin.setObjectName("pushButtonbegin")
        self.gridLayout.addWidget(self.pushButtonbegin, 2, 0, 1, 4)
        self.pushButtonend = QtWidgets.QPushButton(self.tab2)
        self.pushButtonend.setGeometry(QtCore.QRect(380, 160, 151, 41))
        self.pushButtonend.setObjectName("pushButtonend")
        self.pushButtoncontinue = QtWidgets.QPushButton(self.tab2)
        self.pushButtoncontinue.setGeometry(QtCore.QRect(380, 120, 151, 41))
        self.pushButtoncontinue.setObjectName("pushButtoncontinue")
        self.labelcount = QtWidgets.QLabel(self.layoutWidget)
        self.labelcount.setObjectName("labelcount")
        self.gridLayout.addWidget(self.labelcount, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.record_time = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.record_time.setMaximum(72.0)
        self.record_time.setObjectName("record_time")
        self.gridLayout.addWidget(self.record_time, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 3, 1, 1)
        self.record_num = QtWidgets.QLabel(self.layoutWidget)
        self.record_num.setText("")
        self.record_num.setObjectName("record_num")
        self.gridLayout.addWidget(self.record_num, 0, 3, 1, 1)
        self.label_img2 = QtWidgets.QLabel(self.tab2)
        self.label_img2.setGeometry(QtCore.QRect(5, 150, 300,300))
        self.label_img2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img2.setText("")
        self.label_img2.setObjectName("label_img2")
        self.label_3 = QtWidgets.QLabel(self.tab2)
        self.label_3.setGeometry(QtCore.QRect(410, 200, 51, 41))
        self.label_3.setObjectName("label_3")
        self.label_output = QtWidgets.QLabel(self.tab2)
        self.label_output.setGeometry(QtCore.QRect(340, 250, 221, 41))
        self.label_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.label_6 = QtWidgets.QLabel(self.tab2)
        self.label_6.setGeometry(QtCore.QRect(120, 120, 54, 12))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.label_showdata = QtWidgets.QLabel(self.tab3)
        self.label_showdata.setGeometry(QtCore.QRect(10, 10, 600, 350))
        self.label_showdata.setFrameShape(QtWidgets.QFrame.Box)
        self.label_showdata.setText("")
        self.label_showdata.setObjectName("label_showdata")
        self.pushButtonshow = QtWidgets.QPushButton(self.tab3)
        self.pushButtonshow.setGeometry(QtCore.QRect(170, 400, 111, 41))
        self.pushButtonshow.setObjectName("pushButtonshow")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab3)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 400, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab3, "")

        self.btn_chooseDir = QtWidgets.QPushButton(self.tab2)
        self.btn_chooseDir.setObjectName("btn_chooseDir")
        self.btn_chooseDir.setText("选择文件夹")
        self.btn_chooseDir.setGeometry(QtCore.QRect(380, 300, 150, 50))

        self.btn_chooseoDir = QtWidgets.QPushButton(self.tab2)
        self.btn_chooseoDir.setObjectName("btn_chooseDir")
        self.btn_chooseoDir.setText("选择输出文件夹")
        self.btn_chooseoDir.setGeometry(QtCore.QRect(380, 380, 150, 50))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "仪表检测"))
        self.pushButtoncamer.setText(_translate("Form", "摄像头"))
        self.pushButtonexit.setText(_translate("Form", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Form", "预览"))
        self.labelinterval.setText(_translate("Form", "记录间隔（分钟）"))
        self.labeltime.setText(_translate("Form", "记录时间（小时）"))
        self.pushButtonbegin.setText(_translate("Form", "开始记录"))
        self.labelcount.setText(_translate("Form", "剩余次数/总次数"))
        self.label.setText(_translate("Form", "当前进度"))
        self.label_3.setText(_translate("Form", "当前数值"))
        self.label_6.setText(_translate("Form", "识别图片"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "记录"))
        self.pushButtonshow.setText(_translate("Form", "查看"))
        self.pushButton_2.setText(_translate("Form", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("Form", "可视化"))
        self.pushButtonend.setText(_translate("Form", "停止"))
        self.pushButtoncontinue.setText(_translate("Form", "继续"))
